title: hugogomess
email: hugogomes02@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Posts about python, nodejs, backend and web hacking...
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
  - jekyll-seo-tag
